//file:noinspection GroovyAssignabilityCheck
import groovy.json.JsonSlurper


plugins {
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.88'
}

version = "v${mod_version}-mc${mc_version}"
group = mod_group_id
base {
    archivesName = mod_id
}

// Mojang ships Java 21 to end users in 1.21+, so your mod should target Java 21.
java.toolchain.languageVersion = JavaLanguageVersion.of(21)

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"

repositories {
    // Put repositories for dependencies here
    // ForgeGradle automatically adds the Forge maven and Maven Central for you

    // If you have mod jar dependencies in ./libs, you can declare them as a repository like so.
    // See https://docs.gradle.org/current/userguide/declaring_repositories.html#sub:flat_dir_resolver
    // flatDir {
    //     dir 'libs'
    // }
    maven { url 'https://maven.blamejared.com' }

    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
}

dependencies {

    // Example mod dependency with JEI - using fg.deobf() ensures the dependency is remapped to your development mappings
    // The JEI API is declared for compile time use, while the full JEI artifact is used at runtime
    compileOnly "mezz.jei:jei-${mc_version}-common-api:${jei_version}"
    compileOnly "mezz.jei:jei-${mc_version}-neoforge-api:${jei_version}"
    runtimeOnly "mezz.jei:jei-${mc_version}-neoforge:${jei_version}"

    // Example mod dependency using a mod jar from ./libs with a flat dir repository
    // This maps to ./libs/coolmod-${mc_version}-${coolmod_version}.jar
    // The group id is ignored when searching -- in this case, it is "blank"
    // implementation fg.deobf("blank:coolmod-${mc_version}:${coolmod_version}")

    // For more info:
    // http://www.gradle.org/docs/current/userguide/artifact_dependencies_tutorial.html
    // http://www.gradle.org/docs/current/userguide/dependency_management.html

    implementation "maven.modrinth:sodium:mc${mc_version}-0.6.13-neoforge"
}

tasks.register('autoPublish', JavaExec) {
    mainClass = 'net.kapitencraft.kap_lib.publish.AutoPublisher'

    classpath = sourceSets.main.runtimeClasspath
}

tasks.register('gitUpdate', Task) {
    def publishConfig = file('run/PublishCache.txt')

    if (publishConfig.exists()) {
        if (mod_version == publishConfig.text) throw new IllegalStateException("Version ID already published")
    }

    doLast {
        exec {
            commandLine 'git', 'add', '.'
        }

        exec {
            commandLine 'git', 'commit', '-m', 'update ' + mod_version
            ignoreExitValue = true //ensure it doesn't crash when there's nothing to commit
        }
    }
}

var metaProperties = [
        minecraft_version      : mc_version,
        minecraft_version_range: minecraft_version_range,
        neo_version            : neo_version,
        neo_version_range      : neo_version_range,
        loader_version_range   : loader_version_range,
        mod_id                 : mod_id, mod_name: mod_name,
        mod_license            : mod_license, mod_version: mod_version,
        mod_authors            : mod_authors, mod_description: mod_description,
]

tasks.named('processResources', ProcessResources).configure {
    inputs.properties metaProperties

    filesMatching(['pack.mcmeta']) {
        expand metaProperties
    }

    filesMatching(['META-INF/ee-at-neoforge.mods.toml']) { FileCopyDetails fCD ->
        fCD.expand metaProperties
        fCD.setName('neoforge.mods.toml')
    }

    var publishProperties = [
            mod_id: mod_id, mod_name: mod_name,
            mod_version: mod_version, minecraft_version: mc_version,
            neo_version: neo_version
    ]

    inputs.properties publishProperties
    filesMatching(['publish_config.json']) {
        expand publishProperties
    }
}

//region modules
ext.moduleFilters = [
        core: [
                asMod: true,
                extensions: false,
                at: true,
                assets: [
                        '*/lang/en_us.json',
                        'kap_lib/textures/gui/background.png',
                        'kap_lib/textures/gui/red_cross.png',
                        'kap_lib/textures/gui/slot_background.png'
                ]
        ]
]

def modulesDir = file("modules")
modulesDir.eachFileMatch(~/.*\.json/) { file ->
    def moduleName = file.name.replace(".json", "")
    def config = new JsonSlurper().parse(file)

    ext.moduleFilters[moduleName] = config
}

println "Discovered Modules: " + moduleFilters.keySet()

// Include resources generated by data generators.
sourceSets.main {
    resources {
        srcDir 'src/generated/resources'
        exclude 'data/test/**'
        exclude 'META-INF/jarjar/**'
        exclude 'META-INF/dev-neoforge.mods.toml'
        exclude 'META-INF/ee-neoforge.mods.toml'
        exclude 'META-INF/nat-neoforge.mods.toml'
        exclude '.cache'
        moduleFilters.each { String name, val ->
            exclude "kap_lib_${name}.mixins.json"
            exclude "META-INF/accesstransformer-${name}.cfg"
        }
    }
    java { SourceDirectorySet set ->
        moduleFilters.each { String name, val ->
            exclude "net/kapitencraft/kap_lib/${name}/mixin/classes/**"
            exclude "net/kapitencraft/kap_lib/${name}/event/handler/**"
            exclude "net/kapitencraft/kap_lib/${name}/${convertModuleNameSmall(name)}Module.java"
            exclude "net/kapitencraft/kap_lib/${name}/network/${convertModuleNameSmall(name)}Messages.java"
        }
    }
}

static def convertModuleId(String moduleId) {
    String strings = ""
    for (final def mE in moduleId.split("_")) {
        if (strings.isEmpty())
            strings += mE
        else
            strings += mE.capitalize()
    }
    return strings
}

//generate module source sets
sourceSets {
    moduleFilters.each { String name, filter ->
        create(convertModuleId(name)) { SourceSet s ->
            s.java {
                srcDir 'src/main/java'
                include "net/kapitencraft/kap_lib/${name}/**"
            }

            s.resources {
                srcDirs = []
            }
        }
    }
}

sourceSets.configureEach { ss ->
    if (ss.name != "main") {
        tasks.register("jar${convertModuleNameSmall(ss.name)}", Jar) {
            description = "Assembles a jar for ${ss.name}"
            from ss.output
        }
    }
}

dependencies {
    moduleFilters.each { String name, filter ->
        def mName = convertModuleId(name)

        if (filter.compat != null) {
            filter.compat.each { String dep ->
                "${mName}CompileOnly"(sourceSets[convertModuleId(dep)].output)
            }
        }

        if (filter.dependencies != null) {
            filter.dependencies.each { String dep ->
                "${mName}Implementation"(sourceSets[convertModuleId(dep)].output)
            }
        }

        if (name != 'core') {
            "${mName}Implementation"(sourceSets.core.output)
        }
    }
    recipeCompileOnly "mezz.jei:jei-${mc_version}-common-api:${jei_version}"
    recipeCompileOnly "mezz.jei:jei-${mc_version}-neoforge-api:${jei_version}"
    recipeRuntimeOnly "mezz.jei:jei-${mc_version}-neoforge:${jei_version}"
}

//region helper
static def mergeClassName(String moduleName, String postfix) {
    return moduleName + postfix + '.class'
}

static def convertModuleName(String moduleName) {
    String strings = ""
    for (final def mE in moduleName.split("_")) {
        strings += mE.capitalize()
        strings += ' '
    }
    return strings
}

static def convertModuleNameSmall(String moduleName) {
    String strings = ''
    for (final def mE in moduleName.split("_")) {
        strings += mE.capitalize()
    }
    return strings
}
//endregion

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_version
        minecraftVersion = project.mc_version
    }

    moduleFilters.keySet().each { String n ->
        addModdingDependenciesTo(sourceSets."${convertModuleId(n)}")
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }

        moduleFilters.each { String mName, module ->
            if (module.asMod) {
                it.register("${mod_id}_${mName}") {
                    sourceSet sourceSets[convertModuleId(mName)]
                }
            }
        }
    }

    runs {
        // applies to all the run configs below
        configureEach {

            systemProperty 'forge.enabledGameTestNamespaces', mod_id
            // Recommended logging data for a userdev environment
            // The markers can be added/remove as needed separated by commas.
            // "SCAN": For mods scan.
            // "REGISTRIES": For firing of registry events.
            // "REGISTRYDUMP": For getting the contents of all registries.
            systemProperty 'forge.logging.markers', 'REGISTRIES'

            // Recommended logging level for the console
            // You can set various levels here.
            // Please read: https://stackoverflow.com/questions/2031163/when-to-use-the-different-log-levels
            logLevel = org.slf4j.event.Level.WARN
        }

        moduleFilters.each { String name, module ->
            if (module.asMod) {
                create("client${convertModuleNameSmall(name)}") {
                    client()

                    sourceSet = sourceSets[convertModuleId(name)]
                    loadedMods = [mods."${mod_id}_${name}", mods."${mod_id}_core"] + (module.dependencies == null ? List.of() :
                            module.dependencies.stream().map(s -> mods."${mod_id}_${s}").toList())
                    programArguments.addAll '--username', 'Kapitencraft', '--uuid', '00c930fd-9d29-44ca-b614-e5ce6e8bd457'
                }
            }
        }

        serverRequirement {
            server()

            sourceSet = sourceSets.requirement
            loadedMods = [mods.kap_lib_core, mods.kap_lib_requirement]
        }

        client {
            client()

            loadedMods = [mods."${mod_id}"]
            programArguments.addAll '--username', 'Kapitencraft', '--uuid', '00c930fd-9d29-44ca-b614-e5ce6e8bd457'
        }

        kaupenClient {
            client()

            loadedMods = [mods."${mod_id}"]
            programArguments.addAll '--username', 'Kaupenjoe', '--uuid', '665ad10f-5548-4985-986b-b642732ddce0'
        }

        server {
            server()
            programArgument '--nogui'
        }

        data {
            data()
            // example of overriding the workingDirectory set in configureEach above

            sourceSet = sourceSets.main
            loadedMods = [mods."${mod_id}"]

            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            programArguments.addAll '--mod', mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
    }
}

moduleFilters.each { String moduleId, moduleData ->
    String moduleName = convertModuleName(moduleId)
    var tomlProperties = [
            minecraft_version      : mc_version,
            minecraft_version_range: minecraft_version_range,
            loader_version_range   : loader_version_range,
            neo_version            : neo_version,
            mod_license            : mod_license,
            mod_id                 : "${mod_id}_${moduleId}",
            mod_version            : mod_version,
            mod_name               : "${mod_name} ${moduleName}Module",
            mod_authors            : mod_authors,
            mod_description        : "${moduleName}Module of KapLib",
            neo_version_range      : neo_version_range
    ]

    tasks.named("process${convertModuleNameSmall(moduleId)}Resources").configure {
        duplicatesStrategy = DuplicatesStrategy.FAIL

        from (['src/main/resources', 'src/generated/resources']) {
            if (moduleData.assets != null) {
                moduleData.assets.each { String aName ->
                    include "assets/${aName}"
                }
            }

            if (moduleData.data != null) {
                moduleData.data.each { String dName ->
                    include "data/${dName}"
                }
            }

            if (moduleData.asMod) {
                if (moduleData.at) {
                    if (moduleData.extensions) {
                        include 'META-INF/ee-at-neoforge.mods.toml'
                    } else {
                        include 'META-INF/dev-neoforge.mods.toml'
                    }
                    include "META-INF/accesstransformer-${moduleId}.cfg"
                    filesMatching ("META-INF/accesstransformer-${moduleId}.cfg") { FileCopyDetails fCD ->
                        fCD.setName('accesstranformer.cfg')
                    }
                } else {
                    if (moduleData.extensions) {
                        include 'META-INF/ee-neoforge.mods.toml'
                    } else {
                        include 'META-INF/nat-neoforge.mods.toml'
                    }
                }
                filesMatching ([
                        'META-INF/ee-at-neoforge.mods.toml',
                        'META-INF/dev-neoforge.mods.toml',
                        'META-INF/ee-neoforge.mods.toml',
                        'META-INF/nat-neoforge.mods.toml'
                ]) { FileCopyDetails fCD ->
                    fCD.expand tomlProperties
                    fCD.setName('neoforge.mods.toml')
                }
                include "${mod_id}_${moduleId}.mixins.json"
            }
        }
    }

    tasks.named("jar${convertModuleNameSmall(moduleId)}").configure {

        exclude 'data/test'
        exclude 'assets/test'

        if (moduleId != 'core') {
            filesMatching ('META-INF/jarjar/metadata.json') { FileCopyDetails fCD ->
                fCD.expand tomlProperties
            }

            from (tasks.jarCore.archiveFile) {
                into 'META-INF/jarjar'
            }
        }

        archiveClassifier = moduleId
    }

    tasks.register("${convertModuleId(moduleId)}SourcesJar", Jar) {
        group = "build"
        description = "Assembles a sources jar for ${moduleId}"

        archiveClassifier = "${moduleId}-sources"

        from sourceSets[convertModuleId(moduleId)].java
    }
}

tasks.named('assemble').configure {
    dependsOn {moduleFilters.keySet().stream().map { "jar${convertModuleNameSmall(it)}"}.toList()}
    dependsOn {moduleFilters.keySet().stream().map { "${convertModuleId(it)}SourcesJar"}.toList()}
}
//endregion

tasks.named('jar') {
    moduleFilters.keySet().forEach { String moduleId ->

        it.exclude "net/kapitencraft/kap_lib/${moduleId}/mixin/**" //exclude all module mixins
        it.exclude "net/kapitencraft/kap_lib/${moduleId}/event/handler/**"
        it.exclude 'net/kapitencraft/kap_lib/' + convertModuleNameSmall(moduleId) + 'Module.class'

        it.exclude 'net/kapitencraft/kap_lib/' + mergeClassName(moduleId, 'Module')

        it.exclude "${mod_id}_${moduleId}.mixins.json"
    }

    exclude 'publish_config.json'
}

java {
    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}