//file:noinspection GroovyAssignabilityCheck
import groovy.json.JsonSlurper

import java.nio.file.Files

plugins {
    id 'idea'
    id 'com.vanniktech.maven.publish' version '0.33.0'
    id 'signing'
    id 'net.neoforged.moddev' version '2.0.141'
}

ext.convertModuleName = { String moduleName ->
    moduleName
            .split("_")
            .collect { it.capitalize() }
            .join(" ")
}

version = "v${mod_version}-mc${mc_version}"
group = 'io.github.kapitencraft'
base {
    archivesName = mod_id
}

java {
    withSourcesJar()
}

println("Discovered ${subprojects.size()} modules: ${subprojects.name}")

ext.createRequiredClasses = { Project project, String name ->
    String[] files = [
            "src/main/java/net/kapitencraft/kap_lib/${name}",
            "src/main/resources/META-INF"
    ]

    for (final def s in files) {
        File f = project.file(s)

        if (!f.exists()) {
            f.mkdirs()
        }
    }

    String[] sources = [
            "neoforge.mods.toml"
    ]
    File target = project.file("src/main/resources/META-INF")

    for (final def s in sources) {
        File it = rootProject.file("src/main/resources/META-INF/${s}")
        File out = new File(target, it.getName())
        if (!out.exists())
            Files.copy(it.toPath(), out.toPath())
    }
}

subprojects { Project proj ->

    Object moduleData = new JsonSlurper().parse(rootProject.file("modules/${name}.json"))
    proj.ext.data = moduleData

    if (moduleData.type == 'mod')
        rootProject.ext.createRequiredClasses(proj, name)

    String moduleId = mod_id + "_" + name

    String modName = "${mod_name} ${rootProject.ext.convertModuleName(proj.name)} Module"

    apply plugin: 'idea'
    apply plugin: 'com.vanniktech.maven.publish'
    apply plugin: 'net.neoforged.moddev'

    group = rootProject.group
    version = rootProject.version

    java {
        withSourcesJar()
    }

    base {
        archivesName = mod_id + "-" + name
    }

    repositories {
        mavenCentral()

        if (name == 'recipe') {
            maven { url 'https://maven.blamejared.com' }
        }
        if (name == 'enchantment') {
            exclusiveContent {
                forRepository {
                    maven {
                        name = "Modrinth"
                        url = "https://api.modrinth.com/maven"
                    }
                }
                filter {
                    includeGroup "maven.modrinth"
                }
            }
        }
    }

    dependencies {
        if (name != "core" && moduleData.type == 'mod') {
            api(project(":core"))
        }

        if (name == 'enchantment') {
            implementation('maven.modrinth:sorted-enchantments:2.0.0+1.21+neoforge')
        } else if (name == 'recipe') {
            compileOnly "mezz.jei:jei-${mc_version}-common-api:${jei_version}"
            compileOnly "mezz.jei:jei-${mc_version}-neoforge-api:${jei_version}"
            runtimeOnly "mezz.jei:jei-${mc_version}-neoforge:${jei_version}"
        } else if (name == 'publish') {
            implementation('com.google.code.gson:gson:2.10.1')
            implementation('com.google.guava:guava:32.1.2-jre')
            implementation('com.mojang:logging:1.2.7')
            implementation('org.slf4j:slf4j-api:2.0.9')
            implementation('org.jetbrains:annotations:24.1.0')
            api(project(":core"))
        } else if (name == 'datagen') {
            api(project(":core"))
        }

        if (moduleData.compat != null) {
            moduleData.compat.each { String dep ->
                compileOnly(project(":${dep}"))
            }
        }

        if (moduleData.dependencies != null) {
            moduleData.dependencies.each { String dep ->
                api(project(":${dep}"))
            }
        }
    }

    mavenPublishing {
        signAllPublications()
        publishToMavenCentral()

        if (name == 'aggregate') {
            coordinates(group, mod_id, version)

            pom {
                name = "${mod_name} Aggregate Library"
            }
        } else {
            coordinates(group, mod_id + "-" + name, version)

            pom {
                name = modName
            }
        }

        pom {
            description = "Library for (almost) any occasion"
            url = "https://github.com/kapitencraft/kapLib"

            licenses {
                license {
                    name = "MIT License"
                    url = "https://opensource.org/license/mit"
                }
            }

            developers {
                developer {
                    id = "kapitencraft"
                    name = "Kapitencraft"
                    url = "https://github.com/Kapitencraft/"
                }
            }

            scm {
                url = "https://github.com/Kapitencraft/kapLib/"
                connection = "scm:git:git://github.com/Kapitencraft/kapLib.git"
                developerConnection = "scm:git:ssh://git@github.com/Kapitencraft/kapLib.git"
            }
        }
    }

    if (rootProject.hasProperty("signingKey")) {
        signing {
            useInMemoryPgpKeys(
                    new String(Base64.decoder.decode((String) rootProject.findProperty("signingKey"))),
                    rootProject.findProperty("signingPassword")
            )
        }
    }

    var metaProperties = [
            minecraft_version      : mc_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : moduleId, mod_name: modName,
            mod_license            : mod_license, mod_version: mod_version,
            mod_authors            : mod_authors, mod_description: mod_description,
    ]

    proj.tasks.named('processResources', ProcessResources).configure {
        inputs.properties metaProperties

        filesMatching(['pack.mcmeta']) {
            expand metaProperties
        }

        filesMatching(['META-INF/neoforge.mods.toml']) { FileCopyDetails fCD ->
            fCD.expand metaProperties
        }
    }

    if (moduleData.type == 'mod' || moduleData.type == 'game_lib') {
        neoForge {
            version = rootProject.neo_version

            addModdingDependenciesTo sourceSets.test

            parchment {
                mappingsVersion = rootProject.parchment_version
                minecraftVersion = rootProject.mc_version
            }

            mods {
                "${mod_id}" {
                    sourceSet(proj.sourceSets.main)
                }
            }

            runs {
                // applies to all the run configs below
                configureEach {

                    systemProperty 'forge.enabledGameTestNamespaces', mod_id
                    // Recommended logging data for a userdev environment
                    // The markers can be added/remove as needed separated by commas.
                    // "SCAN": For mods scan.
                    // "REGISTRIES": For firing of registry events.
                    // "REGISTRYDUMP": For getting the contents of all registries.
                    systemProperty 'forge.logging.markers', 'REGISTRIES'

                    // Recommended logging level for the console
                    // You can set various levels here.
                    // Please read: https://stackoverflow.com/questions/2031163/when-to-use-the-different-log-levels
                    logLevel = org.slf4j.event.Level.WARN
                }

                client {
                    client()

                    programArguments.addAll '--username', 'Kapitencraft', '--uuid', '00c930fd-9d29-44ca-b614-e5ce6e8bd457'
                }

                kaupenClient {
                    client()

                    programArguments.addAll '--username', 'Kaupenjoe', '--uuid', '665ad10f-5548-4985-986b-b642732ddce0'
                }

                server {
                    server()
                    programArgument '--nogui'
                }

                data {
                    data()
                    // example of overriding the workingDirectory set in configureEach above
                    logLevel = org.slf4j.event.Level.DEBUG

                    // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
                    programArguments.addAll '--mod', moduleId, '--all', '--output', proj.file('src/generated/resources/').getAbsolutePath(), '--existing', proj.file('src/main/resources/').getAbsolutePath()
                }
            }

            if (moduleData.interfaceInjection) {
                interfaceInjectionData.from 'interfaces.json'
                interfaceInjectionData {
                    publish file('interfaces.json')
                }
            }
        }
    }
    if (moduleData.type == 'game_lib') {
        jar {
            manifest {
                attributes([
                        "FMLModType": "GAMELIBRARY"
                ])
            }
        }
    }
    if (data.type == 'game_lib') {
        jar {
            manifest {
                attributes([
                        "FMLModType": "GAMELIBRARY"
                ])
            }
        }
    }
}

// Mojang ships Java 21 to end users in 1.21+, so your mod should target Java 21.
java.toolchain.languageVersion = JavaLanguageVersion.of(21)

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"

tasks.register('autoPublish', JavaExec) {
    mainClass = 'net.kapitencraft.kap_lib.publish.AutoPublisher'

    classpath = sourceSets.main.runtimeClasspath

    systemProperty('modrinthAuth', getProperty('modrinthAuth'))
    systemProperty('curseforgeAuth', getProperty('curseforgeAuth'))
}

tasks.register('gitUpdate', Task) {
    def publishConfig = file('run/PublishCache.txt')

    if (publishConfig.exists()) {
        if (mod_version == publishConfig.text) throw new IllegalStateException("Version ID already published")
    }

    doLast {
        exec {
            commandLine 'git', 'add', '.'
        }

        exec {
            commandLine 'git', 'commit', '-m', 'update ' + mod_version
            ignoreExitValue = true //ensure it doesn't crash when there's nothing to commit
        }
    }
}

repositories {
    maven { url 'https://maven.blamejared.com' }
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
}

dependencies {
    runtimeOnly(project(':publish'))

    subprojects.forEach {
        jarJar(implementation(it))
    }

    compileOnly "mezz.jei:jei-${mc_version}-common-api:${jei_version}"
    compileOnly "mezz.jei:jei-${mc_version}-neoforge-api:${jei_version}"
    runtimeOnly "mezz.jei:jei-${mc_version}-neoforge:${jei_version}"
}

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_version
        minecraftVersion = project.mc_version
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }

    runs {
        configureEach {

            systemProperty 'forge.enabledGameTestNamespaces', mod_id
            // Recommended logging data for a userdev environment
            // The markers can be added/remove as needed separated by commas.
            // "SCAN": For mods scan.
            // "REGISTRIES": For firing of registry events.
            // "REGISTRYDUMP": For getting the contents of all registries.
            systemProperty 'forge.logging.markers', 'REGISTRIES'

            // Recommended logging level for the console
            // You can set various levels here.
            // Please read: https://stackoverflow.com/questions/2031163/when-to-use-the-different-log-levels
            logLevel = org.slf4j.event.Level.WARN
        }

        client {
            client()

            programArguments.addAll '--username', 'Kapitencraft', '--uuid', '00c930fd-9d29-44ca-b614-e5ce6e8bd457'
        }

        kaupenClient {
            client()

            programArguments.addAll '--username', 'Kaupenjoe', '--uuid', '665ad10f-5548-4985-986b-b642732ddce0'
        }

        server {
            server()
            programArgument '--nogui'
        }

        data {
            data()
            // example of overriding the workingDirectory set in configureEach above

            sourceSet = sourceSets.main

            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            programArguments.addAll '--mod', mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
    }
}

tasks.named('processResources', ProcessResources) {
    filesMatching('publish_config.json') {
        expand(
                'mod_id': mod_id,
                'mod_name': mod_name,
                'mod_version': mod_version,
                'minecraft_version': mc_version,
                'neo_version': neo_version
        )
    }
}

tasks.named('assemble').configure {
    dependsOn(subprojects.collect {
        it.tasks.named("build")
    })
}

jar {
    manifest {
        attributes([
                "FMLModType": "GAMELIBRARY"
        ])
    }
}

//tasks.named('javadoc', Javadoc) {
//    for (final def proj in subprojects) {
//        if (proj.ext.data.type != 'mod') continue
//
//        it.source(proj.sourceSets.main.allJava)
//    }
//}

tasks.named('processResources', ProcessResources) {
    var publishProperties = [
            mod_id     : mod_id, mod_name: mod_name,
            mod_version: mod_version, minecraft_version: mc_version,
            neo_version: neo_version
    ]

    inputs.properties publishProperties
    filesMatching(['publish_config.json']) {
        expand publishProperties
    }
}

tasks.withType(Javadoc).configureEach {
    exclude('**/mixin/classes/**/*.java') //exclude mixins from javadoc
}

tasks.withType(ProcessResources).configureEach {
    exclude("**/.cache/**")
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

mavenPublishing {
    signAllPublications()
    publishToMavenCentral()

    coordinates(group, mod_id, version)

    pom {
        name = "${mod_name} Aggregate Library"
        description = "Library for (almost) any occasion"
        url = "https://github.com/kapitencraft/kapLib"

        licenses {
            license {
                name = "MIT License"
                url = "https://opensource.org/license/mit"
            }
        }

        developers {
            developer {
                id = "kapitencraft"
                name = "Kapitencraft"
                url = "https://github.com/Kapitencraft/"
            }
        }

        scm {
            url = "https://github.com/Kapitencraft/kapLib/"
            connection = "scm:git:git://github.com/Kapitencraft/kapLib.git"
            developerConnection = "scm:git:ssh://git@github.com/Kapitencraft/kapLib.git"
        }
    }

}

if (hasProperty("signingKey")) {
    signing {
        useInMemoryPgpKeys(
                new String(Base64.decoder.decode((String) findProperty("signingKey"))),
                findProperty("signingPassword")
        )
    }
}