//file:noinspection GroovyAssignabilityCheck

import groovy.json.JsonSlurper

plugins {
    id 'idea'
    id 'com.vanniktech.maven.publish' version '0.33.0'
    id 'signing'
    id 'net.neoforged.moddev' version '2.0.141'
}

ext.convertModuleName = { String moduleName ->
    moduleName
            .split("_")
            .collect { it.capitalize() }
            .join(" ")
}

version = "v${mod_version}-mc${mc_version}"
group = 'io.github.kapitencraft'
base {
    archivesName = mod_id
}

println("Discovered ${subprojects.size()} modules: ${subprojects.name}")

subprojects { Project proj ->

    Object data = name == 'aggregate' ? [] : new JsonSlurper().parse(rootProject.file("modules/${name}.json"))

    apply plugin: 'idea'
    apply plugin: 'com.vanniktech.maven.publish'
    apply plugin: 'net.neoforged.moddev'

    group = rootProject.group
    version = rootProject.version

    java {
        withSourcesJar()
    }

    base {
        archivesName = mod_id + "-" + name
    }

    mavenPublishing {
        signAllPublications()
        publishToMavenCentral()

        if (name == 'aggregate') {
            coordinates(group, mod_id, version)

            pom {
                name = "${mod_name} Aggregate Library"

                withXml {
                    def deps = asNode().appendNode("dependencies")

                    rootProject.subprojects { Project p ->
                        def dep = deps.appendNode("dependency")
                        dep.appendNode("groupId", project.group)
                        dep.appendNode("artifactId", "kap_lib-${p.name}")
                        dep.appendNode("version", project.version)
                        dep.appendNode("scope", "compile")
                    }
                }
            }
        } else {
            coordinates(group, mod_id + "-" + name, version)

            pom {
                name = "${mod_name} ${rootProject.ext.convertModuleName(proj.name)} Module"
            }
        }

        pom {
            description = "Library for (almost) any occasion"
            url = "https://github.com/kapitencraft/kapLib"

            licenses {
                license {
                    name = "MIT License"
                    url = "https://opensource.org/license/mit"
                }
            }

            developers {
                developer {
                    id = "kapitencraft"
                    name = "Kapitencraft"
                    url = "https://github.com/Kapitencraft/"
                }
            }

            scm {
                url = "https://github.com/Kapitencraft/kapLib/"
                connection = "scm:git:git://github.com/Kapitencraft/kapLib.git"
                developerConnection = "scm:git:ssh://git@github.com/Kapitencraft/kapLib.git"
            }
        }
    }

    if (hasProperty("signingKey")) {
        signing {
            useInMemoryPgpKeys(
                    new String(Base64.decoder.decode((String) findProperty("signingKey"))),
                    findProperty("signingPassword")
            )
        }
    }

    repositories {
        mavenCentral()

        if (name == 'recipe' || name == 'aggregate') {
            maven { url 'https://maven.blamejared.com' }
        }
    }

    dependencies {
        if (name != "core" && data.asMod) {
            api(project(":core"))
        }

        if (name == 'recipe') {
            compileOnly "mezz.jei:jei-${mc_version}-common-api:${jei_version}"
            compileOnly "mezz.jei:jei-${mc_version}-neoforge-api:${jei_version}"
            runtimeOnly "mezz.jei:jei-${mc_version}-neoforge:${jei_version}"
        } else if (name == 'publish') {
            implementation('com.google.code.gson:gson:2.10.1')
            implementation('com.google.guava:guava:32.1.2-jre')
            implementation('com.mojang:logging:1.2.7')
            implementation('org.slf4j:slf4j-api:2.0.9')
            implementation('org.jetbrains:annotations:24.1.0')
            api(project(":core"))
        } else if (name == 'datagen') {
            api(project(":core"))
        } else if (name == 'aggregate') {
            subprojects.each { Project project ->
                if (project.name != 'aggregate')
                    api(project)
            }
        }

        if (data.compat != null) {
            data.compat.each { String dep ->
                compileOnly(project(":${dep}"))
            }
        }

        if (data.dependencies != null) {
            data.dependencies.each { String dep ->
                api(project(":${dep}"))
            }
        }
    }

    var metaProperties = [
            minecraft_version      : mc_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id, mod_name: mod_name,
            mod_license            : mod_license, mod_version: mod_version,
            mod_authors            : mod_authors, mod_description: mod_description,
    ]

    proj.tasks.named('processResources', ProcessResources).configure {
        inputs.properties metaProperties

        filesMatching(['pack.mcmeta']) {
            expand metaProperties
        }

        filesMatching(['META-INF/neoforge.mods.toml']) { FileCopyDetails fCD ->
            fCD.expand metaProperties
        }

        var publishProperties = [
                mod_id     : mod_id, mod_name: mod_name,
                mod_version: mod_version, minecraft_version: mc_version,
                neo_version: neo_version
        ]

        inputs.properties publishProperties
        filesMatching(['publish_config.json']) {
            expand publishProperties
        }
    }

    if (data.asMod || name == 'datagen') {
        neoForge {
            version = rootProject.neo_version

            parchment {
                mappingsVersion = rootProject.parchment_version
                minecraftVersion = rootProject.mc_version
            }

            mods {
                "${mod_id}" {
                    sourceSet(proj.sourceSets.main)
                }
            }

            runs {
                // applies to all the run configs below
                configureEach {

                    systemProperty 'forge.enabledGameTestNamespaces', mod_id
                    // Recommended logging data for a userdev environment
                    // The markers can be added/remove as needed separated by commas.
                    // "SCAN": For mods scan.
                    // "REGISTRIES": For firing of registry events.
                    // "REGISTRYDUMP": For getting the contents of all registries.
                    systemProperty 'forge.logging.markers', 'REGISTRIES'

                    // Recommended logging level for the console
                    // You can set various levels here.
                    // Please read: https://stackoverflow.com/questions/2031163/when-to-use-the-different-log-levels
                    logLevel = org.slf4j.event.Level.WARN
                }

                client {
                    client()

                    programArguments.addAll '--username', 'Kapitencraft', '--uuid', '00c930fd-9d29-44ca-b614-e5ce6e8bd457'
                }

                kaupenClient {
                    client()

                    programArguments.addAll '--username', 'Kaupenjoe', '--uuid', '665ad10f-5548-4985-986b-b642732ddce0'
                }

                server {
                    server()
                    programArgument '--nogui'
                }

                //data {
                //    data()
                //    // example of overriding the workingDirectory set in configureEach above
//
                //    sourceSet = proj.sourceSets.main
//
                //    // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
                //    programArguments.addAll '--mod', mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
                //}
            }
        }
    }
}

// Mojang ships Java 21 to end users in 1.21+, so your mod should target Java 21.
java.toolchain.languageVersion = JavaLanguageVersion.of(21)

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"

tasks.register('autoPublish', JavaExec) {
    mainClass = 'net.kapitencraft.kap_lib.publish.AutoPublisher'

    classpath = sourceSets.main.runtimeClasspath

    systemProperty('modrinthAuth', getProperty('modrinthAuth'))
    systemProperty('curseforgeAuth', getProperty('curseforgeAuth'))
}

tasks.register('gitUpdate', Task) {
    def publishConfig = file('run/PublishCache.txt')

    if (publishConfig.exists()) {
        if (mod_version == publishConfig.text) throw new IllegalStateException("Version ID already published")
    }

    doLast {
        exec {
            commandLine 'git', 'add', '.'
        }

        exec {
            commandLine 'git', 'commit', '-m', 'update ' + mod_version
            ignoreExitValue = true //ensure it doesn't crash when there's nothing to commit
        }
    }
}

repositories {
    maven { url 'https://maven.blamejared.com' }
}

dependencies {
    subprojects.each {
        api(it)
    }

    compileOnly "mezz.jei:jei-${mc_version}-common-api:${jei_version}"
    compileOnly "mezz.jei:jei-${mc_version}-neoforge-api:${jei_version}"
    runtimeOnly "mezz.jei:jei-${mc_version}-neoforge:${jei_version}"
    //implementation(project(":core"))
    //implementation(project(":cooldown"))
    //implementation(project(":inventory_page"))
    //implementation(project(":item"))
}

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_version
        minecraftVersion = project.mc_version
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }

    runs {
        // applies to all the run configs below
        configureEach {

            systemProperty 'forge.enabledGameTestNamespaces', mod_id
            // Recommended logging data for a userdev environment
            // The markers can be added/remove as needed separated by commas.
            // "SCAN": For mods scan.
            // "REGISTRIES": For firing of registry events.
            // "REGISTRYDUMP": For getting the contents of all registries.
            systemProperty 'forge.logging.markers', 'REGISTRIES'

            // Recommended logging level for the console
            // You can set various levels here.
            // Please read: https://stackoverflow.com/questions/2031163/when-to-use-the-different-log-levels
            logLevel = org.slf4j.event.Level.WARN
        }

        client {
            client()

            programArguments.addAll '--username', 'Kapitencraft', '--uuid', '00c930fd-9d29-44ca-b614-e5ce6e8bd457'
        }

        kaupenClient {
            client()

            programArguments.addAll '--username', 'Kaupenjoe', '--uuid', '665ad10f-5548-4985-986b-b642732ddce0'
        }

        server {
            server()
            programArgument '--nogui'
        }

        data {
            data()
            // example of overriding the workingDirectory set in configureEach above

            sourceSet = sourceSets.main

            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            programArguments.addAll '--mod', mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
    }
}

tasks.named('assemble').configure {
    dependsOn(subprojects.collect {
        it.tasks.named("build")
    })
}

tasks.named('jar', Jar) {
    exclude("**/*") //keep empty
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

if (hasProperty("signingKey")) {
    signing {
        useInMemoryPgpKeys(
                new String(Base64.decoder.decode((String) findProperty("signingKey"))),
                findProperty("signingPassword")
        )
    }
}