pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
        }
        maven { url = 'https://maven.parchmentmc.org' }
    }
}

file("./modules").eachFile { File it ->
    String folderName = it.name.replace(".json", "")
    include(":${folderName}")
    project(":${folderName}").projectDir = file("m_${folderName}")
}

rootProject.name = "KapLib${mc_version}"